# Generated by Django 3.0.6 on 2020-08-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('Laboratory_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=2000)),
                ('reviews', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
