# Generated by Django 3.0.6 on 2020-08-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='state_name',
        ),
    ]
